### ISSUE TITLE
bodyParser is deprecated, error

### ISSUE THREAD

**Issue by ksaravindakashyap** [expressjs/body-parser#432] opened 2021-04-16 13:48 UTC
As soon as I write `use.app(bodyParser.json())` I am facing new error as bodyParser is deprecated and it is giving suggestion to 
`import bodyParser` but I am not on typescript to import. Can you help w with this, Thank You.
![Screenshot (569)](https://user-images.githubusercontent.com/68753937/115033822-7c4db200-9ee8-11eb-85cd-14fd7337c561.png)

**Comment by dougwilson** [comment] 2021-04-16 13:49
duplicate of #428

The deprecation message is coming from a third-party tool, unfortunately.

**Closed by dougwilson** 2021-04-16 13:49 UTC
