### ISSUE TITLE
Unable to read JSON POST request parameters 

### ISSUE THREAD

**Issue by neeraj87** [expressjs/body-parser#213] opened 2016-12-19 06:25 UTC
I have a node.js + Express application. It has a webhook that I have provided to a third party service. The service sends a POST request to my webhook with JSON body which looks something like this:

> {"split_info" : "null", "customerName" : "Merchant Name", "additionalCharges" : "null", "paymentMode":"CC", "hash":"a31ff1b91fd9b8ae9c82f38b02348d21fsdfd86cc828ac9a0acf82050996372cc656de3db0fe3bf9af52b73a182a77787241f3e19ec893391607301b03e70db8", "status" : "Release Payment", "paymentId" : "551731" , "productInfo":"productInfo", "customerEmail":"test@gmail.com", "customerPhone":"9876543212", "merchantTransactionId":"jnn", "amount":"100.0", "udf2":"null", "notificationId" :"4", "udf1":"null", "udf5":"null", "udf4":"null", "udf3":"null","error_Message":"No Error"}

Here is their documentation on what kind of data they are sending: https://github.com/payumoney-india/Webhooks/raw/master/Transaction_POST_Format.pdf

I am using body-parser module to read POST data. However when I do req.body it gives [object Object], if I do JSON.stringify(req.body), it gives {} i.e. empty. If I try to access the keys in the response like req.body.paymentMode then it gives undefined.

Here is my router code for the webhook: **mywebhook.js**

```
var express = require('express');
var router = express.Router();

router.post('/success', function(req, res){

    //this is where I need to strip the JSON request
    //req.body or JSON.stringify(req.body) or anything that works
    //if everything is okay then I send
    res.sendStatus(200);

});

module.exports = router;
```

My **app.js** looks like this:

```
var express = require('express');                               
var exphbs = require('express-handlebars');
var router = express.Router();                                  
var bodyParser = require('body-parser');

var mywebhook = require('./routes/mywebhook');  

var app = express(); 

.
.
.
app.use(bodyParser.urlencoded({'extended':'true'})); 
app.use(bodyParser.json({ type: '*/*' }));

app.use('/callwebhook', mywebhook);

.
.
.
so on        
```   

When I do a console.log(req.get('Content-Type')) I get `*/*;charset=UTF-8`

I even included the bodyparser middleware in the router like:
```
router.post('/success', bodyParser.text({type: '*/*'}), function(req, res){
});
```

But this did not help either. What am I doing wrong?

**Comment by dougwilson** [comment] 2016-12-21 17:15
Hi @neeraj87 nothing of what you wrote seems wrong, and I made a small app and using the doc link you gave and the pieces of JS you posted, it worked just fine. What am I missing?

**Comment by neeraj87** [comment] 2016-12-22 04:13
@dougwilson I have no idea. I am perplexed at the same. I even tested the third party's webhook call using hookbin.com and it seems to come through with the POST JSON data.

I also tested using hurl.it where the method is POST and the body is same as above. It does not work there as well, JSON.stringify(req.body) return {} and req.body returns [object Object].

Screenshot: https://drive.google.com/file/d/0B43t-lgy1BmXdDlid3FRZVdVOGM/view?usp=sharing

I am hosting my node.js app on heroku (if this info helps)

**Comment by codeforgeek** [comment] 2016-12-22 07:20
Hey @neeraj87 ,

Is request coming to your node server directly from hook or via proxy such as Nginx ? 

If not, try to remove */* and just use bodyParse.json() and comment URL encoded line for test.

If yes, try to check the proxy parameters.

**Comment by neeraj87** [comment] 2016-12-22 07:47
@codeforgeek The request is coming directly from PayUMoney's (the third party) server. I log into my account and save my webhook URL there. Also, I made the change you suggested and the result is same, empty JSON. I am not sure how we check for proxy parameters.

**Comment by neeraj87** [comment] 2017-01-05 15:32
@dougwilson any idea on this? I am super frustrated on why it isnt working. Let me know if you need more information.

**Comment by dougwilson** [comment] 2017-01-05 16:06
Maybe can I get the source code you are running and a packet capture of the exact request that is incoming to the server?

**Comment by neeraj87** [comment] 2017-01-05 16:30
@dougwilson I just sent you the code for app.js and the paymentWebhook.js on your email address given in your GitHub account. Regarding the packet capture of the exact request, how do I do that?

**Comment by dougwilson** [comment] 2017-01-06 01:15
Hi @neeraj87 sorry I have not responded yet--I'm trying to get an email client set up with my email that will actually not block `.js` files so I can read what you attached :) As for packet capture, I personally use Wireshark: https://www.wireshark.org/

**Comment by dougwilson** [comment] 2017-01-06 03:15
Nothing in the files immediately look wrong. There is a lot going on, so I deleted everything that did not seem relevant and ran it and it seems to work just fine, so understanding exactly what is being sent to your web server via that packet capture would help a lot. Here is the request I made, constructed according to that PDF you linked to:
```
$ curl -H 'Content-Type: application/json; charset=UTF-8' -XPOST -d '{"split_info":"17076370","customerName":"Sharad Lahoti","additionalCharges":"","paymentMode":"CC","hash":"f11af47a8b8cf8846b88f61e8aee9a a678cf30017d7607db1dd07d166b91a5dc5275e441eb2588028b68a82fe3d89a19d56c11061ab846d668321c 80ccab3010","status":"failed","error_Message":"Bank denied transaction on the card.","paymentId":"17076370","productInfo":"productInfo","customerEmail":"cxxxx.xx@gmai l.com","customerPhone":"999999999","merchantTransactionId":"templedonation17076370","amount":"19.0","udf2":"","notificationId":"443","udf1":"","udf5":"","udf4":"" ,"udf3":""}' http://localhost:3000/payment/success

**Comment by neeraj87** [comment] 2017-01-06 03:20
@dougwilson my application is hosted on Heroku, which is the URL I provide to the service as my webhook URL. I do not understand how Wireshark can capture packets sent to server hosted on Heroku. Sorry if this is a stupid question.

**Comment by dougwilson** [comment] 2017-01-06 03:22
I'm not familiar with Heroku, so I really don't know. Is it possible you can run that cURL command against your Heroku instance? What is different between that cURL request and the request the third party is making to your server? Without understanding what the request is that is coming into the server, it's hard to understand what is happening.

**Comment by neeraj87** [comment] 2017-01-06 03:24
thats a good idea. I just ran the curl command on localhost and the body did come in. let me replace the localhost with my heroku url

**Comment by neeraj87** [comment] 2017-01-06 03:31
@dougwilson so here is what I found out.

The curl command works with my heroku url, the JSON body is displayed. However, if I replace the Content-Type from application/json to */* the body is empty.

The provider who calls my webhook sends the request with Content-Type as */*, I even tested this with hurl.it where application/json works but */* gives empty body.

**Comment by dougwilson** [comment] 2017-01-06 03:37
Weird, because the PDF you linked is where I grabbed the Content-Type from. That is not even a valid Content-Type at all, so the only way you're going to get this module to accept that type of non-sense string as a Content-Type is to set the `type` option to a function where you validate the Content-Type manually:
```js
app.use(bodyParser.json({type: function (req) {
  return req.headers['content-type'] === '*/*'
}}))
```

**Comment by neeraj87** [comment] 2017-01-06 03:42
Can I setup this content type in the individual router code instead at the app level? SO in the webhook.js can I do something like:

```
var bodyParser = require('body-parser')

var customParser = bodyParser.json({type: function(req) {
       req.headers['content-type'] === star/star
}}))

router.post('/success', customParser, function(req, res){
	var newTask = {
		idTasks : shortid.generate(),
		Name : 'Content-type: ' + req.get('Content-type'),
		Description : 'JSON body: ' + JSON.stringify(req.body),
		CreatedDateTime : new Date()
	}

	queryHandler.queryRecordsWithParam('insert into Tasks set ?', newTask, function(err, rows){
		if(err) {
			winston.log('info: ', '-------------------- ERROR: ' + err);
			res.sendStatus(500);
		}
		res.sendStatus(200);
	});
});
```

**Comment by dougwilson** [comment] 2017-01-06 03:46
Yes, that should work just fine. Since the incoming request won't match for the first two in your main app, it will get to your router.post above unparsed and then the different type filter should pick it up and parse it for that route.

**Comment by neeraj87** [comment] 2017-01-06 03:51
Tested it with the curl command on localhost and it did not work :(  the body come in empty.

**Comment by dougwilson** [comment] 2017-01-06 03:53
What was the cURL command?

**Comment by neeraj87** [comment] 2017-01-06 03:56
curl -H 'Content-Type: */*; charset=UTF-8' -XPOST -d '{"split_info":"17076370","customerName":"Sharad Lahoti","additionalCharges":"","paymentMode":"CC","hash":"f11af47a8b8cf8846b88f61e8aee9a a678cf30017d7607db1dd07d166b91a5dc5275e441eb2588028b68a82fe3d89a19d56c11061ab846d668321c 80ccab3010","status":"failed","error_Message":"Bank denied transaction on the card.","paymentId":"17076370","productInfo":"productInfo","customerEmail":"cxxxx.xx@gmai l.com","customerPhone":"999999999","merchantTransactionId":"templedonation17076370","amount":"19.0","udf2":"","notificationId":"443","udf1":"","udf5":"","udf4":"" ,"udf3":""}' http://localhost:3000/payment/success

**Comment by dougwilson** [comment] 2017-01-06 03:57
For that request, your custom parser needs to be the following:
```js
var customParser = bodyParser.json({type: function(req) {
       req.headers['content-type'] === '*/*; charset=UTF-8'
}}))
```

**Comment by neeraj87** [comment] 2017-01-06 04:02
That did not work either.

**Comment by dougwilson** [comment] 2017-01-06 04:04
Can you set the `DEBUG` environment variable to the value `body-parser:*` restart your app, run the cURL command against it and paste the output the app prints here?

**Comment by dougwilson** [comment] 2017-01-06 04:07
Nevermind. I didn't notice that when you transferred my original example, you removed the `return` statement. You need to put the `return` there to return a value from the function in your parser:
```js
var customParser = bodyParser.json({type: function(req) {
       return req.headers['content-type'] === '*/*; charset=UTF-8'
}}))
```

**Comment by neeraj87** [comment] 2017-01-06 04:09
```
info: The server has started
  body-parser:urlencoded content-type "*/*; charset=UTF-8" +0ms
  body-parser:urlencoded skip parsing +1ms
  body-parser:json content-type "*/*; charset=UTF-8" +0ms
  body-parser:json skip parsing +0ms
  body-parser:json content-type "*/*; charset=UTF-8" +4ms
  body-parser:json skip parsing +0ms

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/express/lib/response.js:718:10)
    at ServerResponse.contentType (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/express/lib/response.js:551:15)
    at ServerResponse.sendStatus (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/express/lib/response.js:339:8)
    at /Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/routes/paymentWebhook.js:27:7
    at /Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/config/queryHandler.js:28:4
    at Handshake.onConnect (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at PoolConnection.Connection._handleNetworkError (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/mysql/lib/Connection.js:421:18)
    at PoolConnection.Connection._handleConnectTimeout (/Volumes/Macintosh HD 2/GitHub Cloned Repos/violet-admin-dev/node_modules/mysql/lib/Connection.js:417:8)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:92:17)
    at Socket._onTimeout (net.js:326:8)
    at Timer.unrefTimeout [as ontimeout] (timers.js:418:13)
```

**Comment by neeraj87** [comment] 2017-01-06 04:10
oops, hold on, let me add the return and retry.

**Comment by neeraj87** [comment] 2017-01-06 04:13
ok, so i added the return statement and ran the curl command and its the same result, body is empty:

```
var customParser = bodyParser.json({type: function(req) {
	return req.headers['Content-Type'] === '*/*; charset=UTF-8';
}});

router.post('/success', customParser, function(req, res){
	var newTask = {
		idTasks : shortid.generate(),
		Name : 'Content-type: ' + req.get('Content-type'),
		Description : 'JSON body: ' + JSON.stringify(req.body),
		CreatedDateTime : new Date()
	}

	queryHandler.queryRecordsWithParam('insert into Tasks set ?', newTask, function(err, rows){
		if(err) {
			winston.log('info: ', '-------------------- ERROR: ' + err);
			res.sendStatus(500);
		}
		res.sendStatus(200);
	});
});
```

The DEBUG gives the following:

```
body-parser:urlencoded content-type "*/*; charset=UTF-8" +0ms
  body-parser:urlencoded skip parsing +1ms
  body-parser:json content-type "*/*; charset=UTF-8" +0ms
  body-parser:json skip parsing +0ms
  body-parser:json content-type "*/*; charset=UTF-8" +3ms
  body-parser:json skip parsing +0ms
```

**Comment by dougwilson** [comment] 2017-01-06 04:14
It looks like it's because you capitalized the C and T in the function in the word content-type. Please trying just pasting the exact parser function I give above:
```js
var customParser = bodyParser.json({type: function(req) {
       return req.headers['content-type'] === '*/*; charset=UTF-8'
}}))
```

**Comment by neeraj87** [comment] 2017-01-06 04:20
Yes, you are right. I changed it to lowercase c and t and the body comes in. Give me 5 mins and I will deploy this to Heroku and test it on the live webhook URL

**Comment by neeraj87** [comment] 2017-01-06 04:34
@dougwilson  It is working. The actual webhook now gets the data. So the actual problem was with the content type declaration?

**Closed** 2017-01-06 04:35 UTC

**Comment by dougwilson** [comment] 2017-01-06 04:42
That's great to hear! So yes, that would have been the issue. The way the parsers work is that they will only try to parse a request in which they understand the Content-Type. This is mainly so you can stack them (app.use multiple parser types without conflict) and also because you typically don't want to parse a request that's going to fail (Content-Type: text/html is unlikely to ever get through a JSON.parse, for example).

Even though that PDF document you linked to says and even show an example of the Content-Type being application/json; charset=UTF-8 it was not. If they actually used that Content-Type, then you would have not had any issues since bodyParser.json() by default without configuration will look for application/json, since that's the signal of a JSON body.

You ended up getting sent \*/\*; charset=UTF-8 which is not even a valid Content-Type header value period. This is why this module refused to accept it, since that is gibberish :) This module does allow you to setup a function that lets you put any custom logic you want to perform the filtering, so I helped you setup a custom filter to accept that bogus Content-Type value :)

**Comment by neeraj87** [comment] 2017-01-06 04:47
I am gonna have a talk with their tech support today about this. 

Also, I did not know about this.

> This module does allow you to setup a function that lets you put any custom logic you want to perform the filtering

 Glad to find out and I will keep that in mind.

**Comment by ankit939** [comment] 2017-09-03 05:18
I have followed the above step to include the customParser but the issue is not solved. Even then the req.body is empty. I have used strongloop api as payumoney's webhook url. Please help out!

**Comment by 9791836191** [comment] 2019-02-28 12:06
This is my code I am unable to fetch data when i host it on heruko

<!DOCTYPE html>
<html>
<head>
	<title>Fyle Task</title>
</head>
<link rel="stylesheet" type="text/css" href="/stylesheets/csstask.css">
<body >
	<center>
	<h1>Internet Movie Database</h1>
	</div>
	<h2>Search Movie by Name<h2> <input type="text" name="nome" id="nome" placeholder="After typing movie name press enter">
	<p></p>
	</center>
	<table id="tabela" style="font-size: 18pt">
		<tr>
			<th>Description</th>
		</tr>
		<tr>
			<td>Title:</td>
			<td id="title"></td>
		<tr>
			<td>Year:</td>
			<td id="year"></td>
		</tr>
		<tr>
			<td>genre:</td>
			<td id="genre"></td>
		</tr>
		<tr>
			<td>Run Time:</td>
			<td id="time"></td>
		</tr>	
		<tr>
			<td>Director:</td>
			<td id="director"></td>
		</tr>	
		<tr>
			<td>Writer:</td>
			<td id="writer"></td>
		</tr>	
		<tr>
			<td>Language:</td>
			<td id="language"></td>
		</tr>
		<tr>
			<td>Plot: </td>
			<td id="plot"></td>
			</tr>
	</table>
		<p style="font-size: 18pt">Poster</p>
	<img src="" width="300" height="400" id="poster">	
	
	
	
		var obj, dbParam, xmlhttp, myObj, titulo, url, sespaco;
		const inputEle = document.getElementById('nome');
		inputEle.addEventListener('keyup', function(e){
		  	var key = e.which || e.keyCode;
		  	if (key == 13) { 
		    titulo = document.getElementById('nome').value;
		    sespaco = titulo.replace( / /gi,'+');
		    url = "http://www.omdbapi.com/?apikey=65f8bf37&t="+sespaco;
		  	obj = {table: "customers", limit: 20 };
			dbParam = JSON.stringify(obj);
			xmlhttp = new XMLHttpRequest();
			xmlhttp.open("GET", url , true);
			xmlhttp.onreadystatechange = function() {
			  	if (this.readyState == 4 && this.status == 200) {
				   	myObj = JSON.parse(this.responseText);
				       
				    document.getElementById("title").innerHTML = myObj.Title;
				    document.getElementById("year").innerHTML = myObj.Year;
				    document.getElementById("genre").innerHTML = myObj.Genre;
				    document.getElementById("time").innerHTML = myObj.Runtime
				    document.getElementById("director").innerHTML = myObj.Director;
				    document.getElementById("writer").innerHTML = myObj.Writer;
				    document.getElementById("language").innerHTML = myObj.Language;
				    document.getElementById("poster").src = myObj.Poster;
					document.getElementById("plot").innerHTML= myObj.Plot;
			  	}
			};
			xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			xmlhttp.send("x=" + dbParam);
			curl -k -v -H "Content-Type:application/json" -X POST -d '{"session":{"password":"12345678","email":"example@zapserver.com"}}' https://example.com/api/sessions
			}
		});
</script>
</body>
</html>

**Comment by noopurphalak** [comment] 2020-06-11 12:13
Yup, still not the right answer. This issue is not resolved yet...
