### ISSUE TITLE
JSON not showing up req.body returns {}

### ISSUE THREAD

**Issue by joshk132** [expressjs/body-parser#276] opened 2017-10-29 22:30 UTC
I am sending a test webhook to my `/stripe/events` route with no response. Now if I take the request Stripe gives me on the dashboard/test side, and copy that into postman and send that data I can access it. I also get undefined when I try to access something in `req.body` like doing `req.body.data.object.status`

This is the sample response I am trying to send:

    {
      "created": 1326853478,
      "livemode": false,
      "id": "evt_00000000000000",
      "type": "customer.subscription.trial_will_end",
      "object": "event",
      "request": null,
      "pending_webhooks": 1,
      "api_version": "2017-08-15",
      "data": {
        "object": {
          "id": "sub_00000000000000",
          "object": "subscription",
          "application_fee_percent": null,
          "billing": "charge_automatically",
          "cancel_at_period_end": false,
          "canceled_at": null,
          "created": 1509314092,
          "current_period_end": 1511992492,
          "current_period_start": 1509314092,
          "customer": "cus_00000000000000",
          "discount": null,
          "ended_at": null,
          "items": {
            "object": "list",
            "data": [
              {
                "id": "si_1BIOk4285d61s2cIBSeTCXfa",
                "object": "subscription_item",
                "created": 1509314092,
                "metadata": {
                },
                "plan": {
                  "id": "gold",
                  "object": "plan",
                  "amount": 2000,
                  "created": 1394782612,
                  "currency": "cad",
                  "interval": "month",
                  "interval_count": 1,
                  "livemode": false,
                  "metadata": {
                  },
                  "name": "Gold Special",
                  "statement_descriptor": null,
                  "trial_period_days": null
                },
                "quantity": 1
              }
            ],
            "has_more": false,
            "total_count": 1,
            "url": "/v1/subscription_items?subscription=sub_BfkENmTGcpd0dq"
          },
          "livemode": false,
          "metadata": {
          },
          "plan": {
            "id": "gold_00000000000000",
            "object": "plan",
            "amount": 2000,
            "created": 1394782612,
            "currency": "cad",
            "interval": "month",
            "interval_count": 1,
            "livemode": false,
            "metadata": {
            },
            "name": "Gold Special",
            "statement_descriptor": null,
            "trial_period_days": null
          },
          "quantity": 1,
          "start": 1509314092,
          "status": "trialing",
          "tax_percent": null,
          "trial_end": 1509572385,
          "trial_start": 1509313185
        }
      }
    }
 Sending from postman as `text` works but not `JSON` so same issue as stripe.

**Comment by oxcarga** [comment] 2017-11-22 07:22
Did you set "Content-Type" to "application/json"?
Also, for JSON requests, select "raw" option inside "Body" tab and set "JSON(application/json)" in  dropdown on the right side

**Comment by dougwilson** [comment] 2018-01-07 23:25
I'm going to close this since there was no answer to the question above in a month or so. If you can provide more information to reproduce / answer the question I can always re-open 👍

**Closed by dougwilson** 2018-01-07 23:25 UTC
Labels: awaiting more info

**Comment by donggyushin** [comment] 2018-08-26 08:39
Hi~ i was in same situsation with you, but i just figured it out. maybe you should install multer middleware. multer is needed to get data of form-data typed.
