### ISSUE TITLE
req.body empty and or undefined

### ISSUE THREAD

**Issue by 3HMonkey** [expressjs/body-parser#201] opened 2016-10-06 11:07 UTC
Hello guys,

I am currently working on an authentication api using express and body-parser. But I ran into problems with the parser.

For example, here is my app.js:

``` javascript
var morgan = require('morgan');
var bodyParser = require('body-parser');
var passport = require('passport');
var express = require('express');


var app = express();


app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json({ type: 'application/*+json' }));


app.use(morgan('dev'));



app.use(passport.initialize());
require('./config/passport')(passport);

var routes = require('./routes/index');
var register = require('./routes/register');
var authenticate = require('./routes/authenticate');
var dashboard = require('./routes/dashboard');

app.use('/', routes);
app.use('/register', register);
app.use('/authenticate', authenticate);
app.use('/dashboard', dashboard);



// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});


module.exports = app;
```

Now let's have a look at the register.js, located in routes/register.js:

``` javascript
var express = require('express');
var router = express.Router();




router.post('/', function (req, res, next) {
    if (!req.body.email || !req.body.password) {
        console.log(req.body);
        console.log(req.body.email);
        res.json({success: false, message: 'Please enter email and password.'});
    } else {
        var newUser = new User({
            email: req.body.email,
            password: req.body.password
        });

        // Attempt to save the user
        newUser.save(function (err) {
            if (err) {
                return res.json({success: false, message: 'That email address already exists.'});
            }
            res.json({success: true, message: 'Successfully created new user.'});
        });
    }
});

module.exports = router;
```

I am currently sending JSON by using HttpRequester or RESTClient. No matter which one. Both will bring the same bug? I have been printing out "req.body" and "req.body.email" for example.

Case 1:
`
POST http://localhost:3000/register
Content-Type: application/json
{
"email":"testmail@test.com",
"password":"123456"
}
`
Outputs:
`
{}
undefined
POST /register 200 0.350 ms - 62
`

Case 2
Same with url-encoded
`
POST http://localhost:3000/register
Content-Type: application/x-www-form-urlencoded
{
"email":"testmail@test.com",
"password":"123456"
}
`
Outputs:
`
{ '{\n"email":"testmail@test.com",\n"password":"123456"\n}': '' }
undefined
POST /register 200 1.756 ms - 62
`
But why undefined?

Case 3
Working like normal post parameters
`
POST http://localhost:3000/register
Content-Type: application/x-www-form-urlencoded
email=testmail@test.com
`
Outputs:
`
{ email: 'testmail@test.com' }
testmail@test.com
POST /register 200 1.502 ms - 62
`
I personally don't know why it is not parsing the json object.  Maybe you know an answer?

**Comment by dougwilson** [comment] 2016-10-07 00:09
I think the issue is from your ` type: 'application/*+json' ` above. What are you trying to achieve with that?

**Comment by 3HMonkey** [comment] 2016-10-07 06:14
Hello and thank you for your quick answer.

I used `type: 'application/*+json'` for testing purposes. By the way, it seems that just `bodyParser.json()` ignores the JSON sent because with the empty `bodyParser.json()` I am getting an "no view engine error", so I tried out the different settings which are documented like the setting of the type.

**Comment by dougwilson** [comment] 2016-10-20 13:30
I'm really not sure, especially since this module does not produce that view engine error. I can use JSON just fine, and so can the tests. Perhaps you can provide a small, complete app that demonstrates the issue, along with complete instructions on how to make a request to it. If I can reproduce, I can debug it, otherwise, you are absolutely welcome to make a pull request with a possible fix :)

**Comment by mkeggen-iforium** [comment] 2016-10-31 09:12
Hi

We use body-parser in one our projects which has worked perfectly for over a year.  Last week one of the servers was accidentally upgraded from Node 4.5 to 6.9.

After that upgrade req.body had stopped being populated and our project started failing.

We reverted back to Node 4.5 and will need to investigate this further to determine the actual underlying issue to why the body parser stopped populating after the upgrade.

Thought I would mention it in case anyone else has anything to input on this thread

**Comment by dougwilson** [comment] 2016-11-12 21:29
I'm going to close this issue since there hasn't been any response to help me reproduce to figure anything out.

**Closed by dougwilson** 2016-11-12 21:29 UTC
Labels: question

**Comment by GiovaniGil** [comment] 2017-04-04 14:12
Thank you for share your problem and solution. It help me a lot. Cheers!!!

**Comment by jiteshkaranjkar** [comment] 2017-07-01 18:22
just in case if someone is still looking for a solution
try this, since it worked for me first declare app and then the body parser, since bodyparser is used with in app

const app = express();
const bodyParser = require('body-parser');

then have these line below

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: true}))

**Comment by arenddeboer** [comment] 2017-07-12 08:53
Thanks @jiteshkaranjkar. Even though it sounds obvious, I got this error when using the serverMiddleware option in nuxt.config.js which somehow messes up the middleware registration sequence.

**Comment by abbaxee** [comment] 2017-09-05 15:28
I am having the same issue right now

**Comment by Shyles** [comment] 2018-02-16 12:59
@jiteshkaranjkar saved my day.

**Comment by ltphen** [comment] 2018-02-16 19:30
Hello I have the same problems . 
Here is my code 
`var app = require('express')();
	var bodyParser = require('body-parser');  

	app.use(bodyParser.json()); 
	app.use(bodyParser.urlencoded({ extended: true }));


	app.post("/post", function (req, res){
		console.log(res.body),
		res.send(null);
	})

	app.listen(3000, () => {
	  console.log('App listening on port 3000');
	});
`
But i still have undefined as response

**Comment by jayapalu** [comment] 2018-02-26 04:27
In headers pass 'Content-Type:application/json'

**Comment by damanasija** [comment] 2018-04-09 09:32
I'm facing a similar problem when using body-parser.

When i use the following code:

`const bodyParser = require('body-parser');`
 in Node server, this code:- 
`app.post("/", (req, res) => {
    let name = req.body.name;
    res.send(`value of name recieved is ${name}`);
});`
it works fine but it gives me some kind warning in the console when running the app.js file:- 

**Warning:-** 
`body-parser deprecated bodyParser: use individual json/urlencoded middlewares app.js:6:9
body-parser deprecated undefined extended: provide extended option node_modules\body-parser\index.js:105:29`


My client :-`
`
<script>
    document.getElementById("button").addEventListener('click', postName);
    
    function postName(){
        console.log(`clicked`);
        let user = {
            name: document.getElementById("name").value
        }
        let myJsonString = JSON.stringify(user);
        xhr = new XMLHttpRequest();
        
        xhr.open("POST", "/", true);
        xhr.setRequestHeader("Content-type", "application/json");

        xhr.onload = function(){
            console.log(`called`);
            if(this.status == 200){
                document.getElementById("message").innerText = this.responseText;
                console.log(this.responseText);
            }
            else
                console.log(`error = ${this.status}`);
        }
        xhr.send(myJsonString);
    }
</script>
`

I'm using vannila javascript. But my concern is that i learnt to use body parser like this:-

`app.use(bodyParser.urlencoded({extended: true}));`

this gives me an empty req.body object at the server end. Please help me out.

**Comment by Ajay2709** [comment] 2018-04-17 01:57
I tried everything mentioned above but still getting {} in body.
My app.js:
`var express = require('express');
var app = express();
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var path = require("path");


app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());

app.get('/signup',function(req, res){
  console.log("redirected to signup");
  //res.sendFile(path.join(__dirname+'/views/signup.html'));
  res.render('signup');
});


app.post('/signup/submit', function(req, res, next){
  console.log("in signup submit");
  console.log(req.body); // getting empty body here
});
`

**Comment by CarlosRodrigues** [comment] 2018-04-19 12:47
Try to send the "Content-Type:application/json" header when you post data to your endpoint, @Ajay2709

**Comment by dougwilson** [comment] 2018-05-13 15:01
I'm locking this issue because no one watches closed issues. Open a new issue describing your issue with clear steps to reproduce and we can help or open a pull request to fix issues you found.
