### ISSUE TITLE
Quite a few tests breaking on node.js master / v6.0-rc

### ISSUE THREAD

**Issue by TheAlphaNerd** [expressjs/body-parser#167] opened 2016-04-20 19:29 UTC
The v6.0 release is planned for next week and it would appear there are quite a few broken tests.

A few of them are related to changing error messages, but a few appear to not be as simple to fix. I am digging into it right now.

**Comment by dougwilson** [comment] 2016-04-20 19:38
Thanks for the heads-up, @TheAlphaNerd! I don't see the RC in http://nodejs.org/dist/ where would I download Windows binaries for the RC?

Ping @expressjs/express-tc in case someone wants to help take a look as well.

**Comment by TheAlphaNerd** [comment] 2016-04-20 19:40
you can find the rc at --> https://nodejs.org/download/rc/v6.0.0-rc.3/

I'm already in the process of putting together a patch to hopefully fix as much as possible. I'll update in here if I'm not able to solve this quickly by myself

**Comment by jonathanong** [comment] 2016-04-20 19:41
thank you @TheAlphaNerd!

**Comment by TheAlphaNerd** [comment] 2016-04-20 19:50
Fixed easily enough and PR sent. The deeper problems were due to having an out of date repo (updated remote but forgot to merge)

**Comment by jasnell** [comment] 2016-04-20 19:53
I'm looking to cut the v6.0.0 release on Tuesday the 26th (likely later in the day). So there are any additional regressions that pop up, definitely let us know in the nodejs/node issue tracker ASAP. v6.0.0 is being cut directly off master so if master works, it should be good to go.

**Comment by dougwilson** [comment] 2016-04-21 17:05
@TheAlphaNerd I'm not able to run Mocha on any of my repositories because I'm encountering the bug https://github.com/nodejs/node/commit/75487f0db80e70a3e27fabfe323a33258dfbbea8 in that RC you linked me to. Any idea when a new RC will be released that includes that fix?

**Comment by TheAlphaNerd** [comment] 2016-04-21 17:09
@dougwilson new RC is planned for this afternoon 

/cc @jasnell

**Comment by dougwilson** [comment] 2016-04-22 17:39
Hey @TheAlphaNerd, I was looking in https://nodejs.org/download/rc/ for the RC4 but don't see it yet. I've been trying to do some things with the existing RC, but without having a working mocha it's really hard. I've been manually hacking the installed mocha in each project over and over again, which is tedious.

**Comment by jasnell** [comment] 2016-04-22 17:42
RC4 should hit this afternoon. The RC's are being built from a branch cut directly off of master, however, so if you grab the current master and test there you'd be testing exactly what's going to be in RC4

**Comment by dougwilson** [comment] 2016-04-22 17:45
Thanks, @jasnell. From https://github.com/nodejs/node/blob/master/BUILDING.md I need to have Python installed to run this build. I cannot install this on my work machine, so it will have to wait until sometime when I can do this on my personal machine I guess :/

**Comment by jasnell** [comment] 2016-04-22 17:46
Ok. I'll be kicking the RC build off likely around noon Pacific. Shouldn't
take too long to build.

**Comment by TheAlphaNerd** [comment] 2016-04-22 18:04
@dougwilson I kicked off a test release based on the head of master --> https://nodejs.org/download/test/v6.0.0-test201604220e7d57af35/

It is pretty much the equivalent of you building locally. Tar balls are in there now for linux / osx / windows. The headers will be put in there as soon as the pkg installer is built (should be done very soon). 

You may want to wait for the rc, but wanted to give you an option just in case the timing didn't sync up

**Comment by dougwilson** [comment] 2016-04-22 18:08
Thanks, @TheAlphaNerd, https://nodejs.org/download/test/v6.0.0-test201604220e7d57af35/win-x86/ works just fine for me :)

**Comment by TheAlphaNerd** [comment] 2016-04-22 18:09
!

**Closed** 2016-05-06 04:50 UTC
Labels: tests
