### ISSUE TITLE
Wrong GeoJSON parsing

### ISSUE THREAD

**Issue by nenriquez** [expressjs/body-parser#399] opened 2020-05-19 12:00 UTC
1. Create an app using express and body-parser.

```
...
"dependencies": {
 "body-parser": "^1.19.0",
 "express": "^4.16.2",
...
```

```
const express = require('express')
const app = express()
const bodyParser = require('body-parser')

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false}));

app.post('/', function (req, res, next) {
  console.log(`parsed Body: ${JSON.stringify(req.body)}`)
  res.sendStatus(200)
})
```

2. Post a GeoJSON content.

```
curl 'http://localhost:4000/' -X 'POST' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Origin: http://localhost:3000' \
  --data-binary '{"id":6370,"profile":"","ring":{"coordinates":[[-100.18268425106655,25.709377420641147],[-100.14649463915254,25.70622765250316],[-100.11260697904217,25.69979123253907],[-100.1165640637466,25.668318646354635],[-100.1335842201762,25.68158247498974],[-100.14813962151203,25.656932196555857],[-100.19132040845507,25.668053252899142],[-100.18268425106655,25.709377420641147]],"type":"LineString"},"minutes":null,"kms":null,"subsidiary_location_id":6600,"created_at":"2020-05-19T00:18:26.269Z","updated_at":"2020-05-19T00:18:26.269Z","isIso":false}' \
  --compressed
```

3. Note that coordinates are parsed as json dict instead of array.
```
{
   "id":6370,
   "profile":"",
   "ring":{
      "coordinates":[
         {"0":-100.18268425106655,"1":25.709377420641147},
         {"0":-100.14649463915254,"1":25.70622765250316},
         {"0":-100.11260697904217,"1":25.69979123253907},
         {"0":-100.1165640637466,"1":25.668318646354635},
         {"0":-100.1335842201762,"1":25.68158247498974},
         {"0":-100.14813962151203,"1":25.656932196555857},
         {"0":-100.19132040845507,"1":25.668053252899142},
         {"0":-100.18268425106655,"1":25.709377420641147}
      ],
      "type":"LineString"
   },
   "minutes":null,
   "kms":null,
   "subsidiaryLocationId":6600,
   "createdAt":"2020-05-19T00:18:26.269Z",
   "updatedAt":"2020-05-19T00:18:26.269Z",
   "isIso":false
}
```

![Screenshot 2020-05-19 at 08 59 52](https://user-images.githubusercontent.com/4296223/82323925-22c6c580-99af-11ea-90b6-fc40f146921a.png)

**Comment by jonchurch** [comment] 2020-05-28 19:30
I can't reproduce this. Using the code you supplied I am getting arrays.

Closing for now, but if you create a reproduction I'm happy to reopen 👍

**Closed by jonchurch** 2020-05-28 19:30 UTC
