### ISSUE TITLE
specified encoding unsupported

### ISSUE THREAD

**Issue by miriame** [expressjs/body-parser#200] opened 2016-10-06 07:10 UTC
Hi,
I'm a beginner with nodejs/expressjs and try to run a POST request with body-parser middleware as:

``` js
app.use(bodyParser.json({
    inflate: true
}));
app.use(bodyParser.urlencoded({ extended: true, inflate: true }));
```

 but get the error: 
"specified encoding unsupported".

the response headers:
Connection →keep-alive
Content-Length →176
Content-Type →application/json; charset=utf-8
Date →Thu, 06 Oct 2016 06:58:56 GMT
X-Powered-By →Express

any idea what had I missed?

**Comment by dougwilson** [comment] 2016-10-06 22:39
Hi @miriame the error depends on what your request looks like. Can you show what the request you're making is?

**Comment by miriame** [comment] 2016-10-07 09:33
Hi,
thank you for the quick answer.
the request is made by angular service:
return $resource(appSettings.apiServiceNodeUri + 'api/....')

**Comment by dougwilson** [comment] 2016-10-13 02:49
Hi @miriame I have never used Angular before, so don't really understand what that means. Would it be possible to use a tool like Fiddler (http://www.telerik.com/fiddler) to capture the request/response that is not working and post the capture here? That would help trying to figure out why you are having this issue.

**Comment by dougwilson** [comment] 2016-12-21 17:16
Closing since I never heard anything back.

**Closed by dougwilson** 2016-12-21 17:16 UTC

**Comment by greyd** [comment] 2017-03-28 13:57
Hi,
I guess I've found the cause for this issue. The thing is in "Content-Type" header when you try to assign charset in it.
this works perfectly fine
```js
'Content-Type': 'application/json'
```
however, this won't work
```js
'Content-Type': 'application/json; charset=utf-8;',
```

**Comment by dougwilson** [comment] 2017-03-28 14:11
Hi @greyd we do support allowing the charset to be set in the content-type header, but the header you posted above is actually invalid per the HTTP RFC, you need to remove that trailing `;` character, as it signals the start of a new parameter, but since none follows, the assumption is that the header has been truncated.

**Comment by greyd** [comment] 2017-03-28 14:19
@dougwilson That works. I never thought that this semicolon could be a problem. Thanks for the explanation.
