### ISSUE TITLE
When encoding is not present body-parser will fail to decode result returns {} 

### ISSUE THREAD

**Issue by oodboo** [expressjs/body-parser#174] opened 2016-05-22 08:51 UTC
Issue:
When angular2 sends REST request (json object) by default it will send request with following header:
    **Content-Type: text/plain;charset=UTF-8**
result will be: {}

If I change content header to:
    **Content-Type: application/json**
again result will be: {}

It will work if content header is changed to:
    **Content-Type: application/json; charset=utf-8**
result will be {id:-1, name:"xxxx"}

As far as I was willing to track this issue in your json.js file there is ... 
```
function jsonParser(req, res, next) {
    ...
    >> if (!shouldParse(req)) {    

function typeChecker(type) {
  return function checkType(req) {
    return Boolean(typeis(req, type))
  }
}
```
checkType() for the request is returning false ...

First I have thought that there is issue with charset, but you are defaulting that to UTF-8.
There is something wrong with way how typeis determining is something of the requested type or not.

"application/json" is valid content type and this should work ...

**Comment by dougwilson** [comment] 2016-05-22 18:24
Hi @oodboo, I'm not able to replicate your issue, and almost all our tests don't even provide the `charset`, so I'm not sure what's going on. Can you provide all the following?

1. What version of Node.js are you using?
2. What version of this module are you using?
3. Provide complete server-side code that reproduces the issue. It must be self-contained such that I can copy and paste the code into a file and run it to have a server that reproduces the issue. Please use as few other modules besides this one as possible in order to reproduce the issue, as the more there are, the harder it is going to be to diagnose.
4. Provide the exact steps needed to reproduce the issue. For example, this may be a `cURL` or similar command to make to the server provided in number 3. Explain what we will see when we hit the issue and what we should see if the issue wasn't there.

Barring all that, you're of course welcome to debug into the issue and provide thoughts onto what is causing the issue beyond that `checkType` is returning `false` (we can't fix it until we know why that is, and in order for us to understand why, we need to full inputs for that function to run through it ourselves to debug) or provide a pull request with a suggested fix!

**Comment by oodboo** [comment] 2016-05-23 23:13
@dougwilson give me some time, currently busy with something else, will get back to you ...

**Comment by dougwilson** [comment] 2016-05-23 23:54
No problem. All my testing has come up without being able to reproduce. In order to not put pressure on you, I will close this issue as "cannot reproduce" until you are able to fulfill the information above, at which case I will happily reopen the issue!

**Closed by dougwilson** 2016-05-23 23:54 UTC

**Comment by oodboo** [comment] 2016-05-24 00:05
Although there are two thing worth considering why 'application/javascript' is not valid JSON, and also if headers are wrong I think it would be more valuable if you throw exception.
If some method is expecting JSON and it is parsed for it, it would be less time wasting if exception would be thrown -saying that headers are wrong. Instead of turning to debugger and boggling about why a result is empty object {}

**Comment by dougwilson** [comment] 2016-05-24 00:12
I'm not sure how that would work. If we threw an exception, how would you be able to use more than a single parser? For example, if you use a JSON parser then use a urlencoded parser, then requests with the urlencoded content type would cause the JSON parser to throw an error, because it does not understand the header.

I'm sorry, but your suggestion is flawed and will break the entire way this module works. Perhaps we can implement better debug() calls? Did the current debug() calls help or what kind of addition can we make to them to help in your situation?

**Comment by dougwilson** [comment] 2016-05-24 00:19
Also, it may be useful to know that on the 2.x branch, we changed the way that a failed header match works, and no longer provide an empty object. Can you provide feedback on that change? Does it make it easier to figure out, harder, or no difference?

Also, I hope that the readme makes it clear what an empty object means and when it happens. Perhaps you can also provide feedback on our readme? What would make it better?

**Comment by dougwilson** [comment] 2016-05-24 00:21
I'm also really confused now on what you are saying the issue is. In your initial post you said that not having the charset is what was making the difference. In your examples, you are using application/json. Not until your last response did you mention another type like 'application/javascript'. How can I help when the issue description keeps changing?

**Comment by oodboo** [comment] 2016-05-24 06:46
Above I mentioned additional issues connected with the header, and in all cases I have found that mainly issue is returning empty result. .

I will try to reproduce the issue I have mentioned today.
