### ISSUE TITLE
HTTP:413 Request Entity Too Large

### ISSUE THREAD

**Issue by chelsh** [expressjs/body-parser#235] opened 2017-03-28 00:19 UTC
app.use(bodyParser.json({limit: '50mb'}));
    app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));

i post more data,but happen error:HTTP:413 Request Entity Too Large.

ps: node version : v5.1.1
    body-parser: 1.17.1

**Comment by dougwilson** [comment] 2017-03-28 00:50
Hi @chelsh when the request body is larger than your configured limit (50mb in your example), then an `Error` object is constructed and passed on to your Express error handing middleware. By default this will case a 413 Request Entity Too Large response. I hope this helps :) !

**Comment by chelsh** [comment] 2017-03-28 01:31
but my data is not larger than 50M

**Comment by chelsh** [comment] 2017-03-28 01:36
i post a array,the array size is 70

**Comment by chelsh** [comment] 2017-03-28 01:37
![image](https://cloud.githubusercontent.com/assets/10752360/24384999/2015c636-139a-11e7-9506-dfb698516e81.png)

**Comment by chelsh** [comment] 2017-03-28 02:09
how can i do :)

**Comment by dougwilson** [comment] 2017-03-28 12:23
Hi @chelsh very sorry, I misunderstood your initial post. I can take a look, but need more information. Can you please provide all the following?

1. The version of Node.js you are using
2. The version of this module you are using.
3. A complete Node.js app I can run that will reproduce the issue
4. A complete set of instructions for how to make the specific request (and get the 413 response) back from your app

Thank you!

**Comment by steveskimmel** [comment] 2017-03-31 13:58
Hi, 

I am also getting the same error on a get request with 2 query parameters:

Error: request entity too large
    at readStream (/opt/proximityid/app/node_modules/body-parser/node_modules/raw-body/index.js:196:17)
    at getRawBody (/opt/proximityid/app/node_modules/body-parser/node_modules/raw-body/index.js:106:12)
    at read (/opt/proximityid/app/node_modules/body-parser/lib/read.js:76:3)
    at jsonParser (/opt/proximityid/app/node_modules/body-parser/lib/types/json.js:127:5)
    at Layer.handle [as handle_request] (/opt/proximityid/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/proximityid/node_modules/express/lib/router/index.js:317:13)
    at /opt/proximityid/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/proximityid/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/proximityid/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/opt/proximityid/app/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/opt/proximityid/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/proximityid/node_modules/express/lib/router/index.js:317:13)
    at /opt/proximityid/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/proximityid/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/proximityid/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/opt/proximityid/node_modules/express/lib/middleware/init.js:40:5)

**Comment by dougwilson** [comment] 2017-03-31 15:04
Hi @steveskimmel  I can take a look, but need more information. Can you please provide all the following?

1. The version of Node.js you are using
2. The version of this module you are using
3. A complete Node.js app I can run that will reproduce the issue
4. A complete set of instructions for how to make the specific request (and get the 413 response) back from your app

Thank you!

**Comment by toddmedema** [comment] 2017-04-03 15:38
Also getting this error. Our app works fine with submissions up to 100kb, but breaks above 100kb. This is as expected given that the default limit is 100kb, but increasing the limit doesn't seem to do anything.

node v6.9.5
body parser v1.17.1

This is how I'm trying to set the limit:
```
app.use(bodyParser.urlencoded({ extended: true, limit: '5mb' }));
```

Oddly, when I log the limit here - https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L53 - it correctly catches the increased limit. But, I still get the error....

The full error:
```
  "stack": [
    "Error: request entity too large",
    "    at readStream (/Users/toddmedema/expedition-quest-creator/node_modules/raw-body/index.js:196:17)",
    "    at getRawBody (/Users/toddmedema/expedition-quest-creator/node_modules/raw-body/index.js:106:12)",
    "    at read (/Users/toddmedema/expedition-quest-creator/node_modules/body-parser/lib/read.js:76:3)",
    "    at Layer.textParser (/Users/toddmedema/expedition-quest-creator/node_modules/body-parser/lib/types/text.js:86:5)",
    "    at Layer.wrappedHandle (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/instrumentation/express.js:598:19)",
    "    at textParser (eval at wrapHandle (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/instrumentation/express.js:440:19), <anonymous>:4:28)",
    "    at Layer.handle (/Users/toddmedema/expedition-quest-creator/node_modules/express/lib/router/layer.js:95:5)",
    "    at Layer.wrapped (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)",
    "    at Layer.wrappedLayerHandleRequest [as handle_request] (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/instrumentation/express.js:364:14)",
    "    at trim_prefix (/Users/toddmedema/expedition-quest-creator/node_modules/express/lib/router/index.js:317:13)",
    "    at /Users/toddmedema/expedition-quest-creator/node_modules/express/lib/router/index.js:284:7",
    "    at Function.process_params (/Users/toddmedema/expedition-quest-creator/node_modules/express/lib/router/index.js:335:12)",
    "    at Function.cls_wrapProcessParams [as process_params] (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/instrumentation/express.js:382:29)",
    "    at next (/Users/toddmedema/expedition-quest-creator/node_modules/express/lib/router/index.js:275:10)",
    "    at wrapped (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)",
    "    at cleanup (/Users/toddmedema/expedition-quest-creator/node_modules/newrelic/lib/instrumentation/express.js:377:54)"
  ],
```


This is running on the open source Expedition Quest Creator: https://github.com/ExpeditionRPG/expedition-quest-creator

The error is specifically caused by trying to publish a large block of text using a regular jQuery post, such as this: https://github.com/ExpeditionRPG/expedition-quest-creator/blob/master/app/actions/quest.tsx#L148-L151

**Comment by dougwilson** [comment] 2017-04-03 15:45
Hi @toddmedema it's possible you may have multiple, conflicting body parsers registered. I can take a look, but need to be able to run your code. Can you please supply the following?

1. A complete Node.js app I can run that will reproduce the issue
2. A complete set of instructions for how to make the specific request (and get the 413 response) back from your app

Thank you!

**Comment by dougwilson** [comment] 2017-04-03 15:48
@toddmedema if this is your setup in your app: https://github.com/ExpeditionRPG/expedition-quest-creator/blob/23b72809f36171f279ef637be975aacacd1f047f/app.js#L22-L24 then the issue is the following:

the first body parser is setup to accept `*/*`; this is everything, so the next two parsers will never get invoked. That first parser is where you're hitting the limit, if you're not increasing it.

**Comment by dougwilson** [comment] 2017-04-03 15:52
I'm going to close this issue because since normal operation is a 413 when over the limit, and no one has ever provided any answers to my question and this is just turning into an issue that is just endlessly getting "me toos" without any helpful information. Since @toddmedema had something with code, I was able to help there, but it's been 7 days waiting for a response to to OP.

**Closed by dougwilson** 2017-04-03 15:52 UTC
Labels: awaiting more info

**Comment by mlibre** [comment] 2017-10-07 17:17
fixed for me by adding:
`app.use( body_parser({limit: '100mb'}) );`
NOT:
~~`health.use( body_parser.josn({limit: '100mb'}) );`~~

**Comment by Celadora** [comment] 2017-12-19 02:12
We ran into this problem today, and it turned out to be a configuration issue with Nginx. 

Edit this file:
`sudo nano /etc/nginx/nginx.conf`

Add this line inside the http block:
`client_max_body_size 5M;`

Then restart Nginx
`sudo service nginx restart`

**Comment by coderxx** [comment] 2018-07-14 10:11
This fixes the issue.

```
const bodyParser = require('body-parser');

// Tell the bodyparser middleware to accept more data
app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
```
