### ISSUE TITLE
Crash, if first character is "{" but json is still invalid

### ISSUE THREAD

**Issue by tonila** [expressjs/body-parser#79] opened 2015-02-01 06:06 UTC
Hi,

I came up with an error, where client tried to post "javascript", not JSON to the express server.

e.g. body was

    { key: "value" }

This caused express app probably crashed and sent error code 0 back to client.

This affects only json body parser

**Comment by dougwilson** [comment] 2015-02-01 06:09
Hi! Please post what version of this module you are using, which version of Node.js you are using, and a full example app that I can post that payload to that will cause a crash. I'm not able to reproduce the issue.

**Comment by tonila** [comment] 2015-02-01 07:06
I am not able to reproduce this either. I get error 400 with detailed message. I actually got this report from a client. It seems this needs more investigation. I will get back to you if I am able to reproduce this.

**Comment by dougwilson** [comment] 2015-02-04 04:40
Thanks for the update, @tonila

**Comment by dougwilson** [comment] 2015-02-13 04:49
@tonila I'm closing this since it's been a while. If you have determined anything actionable, please let me know and I can re-open the ticket :)

**Closed by dougwilson** 2015-02-13 04:49 UTC
Labels: question
