### ISSUE TITLE
bodyParser.urlencoded middleware adds empty object to req.body even if type is not met

### ISSUE THREAD

**Issue by skleeschulte** [expressjs/body-parser#366] opened 2019-07-27 10:40 UTC
From the docs of `bodyParser.urlencoded`: 
> The type option is used to determine what media type the middleware will parse. [...] Defaults to application/x-www-form-urlencoded.

So I expected `bodyParser.urlencoded` to do nothing if `Content-Type` is not `application/x-www-form-urlencoded`. But `bodyParser.urlencoded` still adds an empty object to `req.body`, even if the type is not met. This way it gets unnecessarily hard to use multiple body parser for different types and check for an empty body.

Seeing that changing this behaviour might break existing apps, I'd suggest to add an option to configure this behaviour and maybe change the default in the future. What do you think?

**Comment by dougwilson** [comment] 2019-07-27 13:42
Duplicate of #269

**Closed by dougwilson** 2019-07-27 13:42 UTC
