### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by kirillgroshkov** [expressjs/body-parser#368] opened 2019-08-15 09:54 UTC
Related to: https://github.com/expressjs/body-parser/issues/329

We want to have control over timeout of `body-parser`, to give it some limited time to receive the request body, or fail with a timeout. Right now there's no way/option to do that. Or am I missing something?

**Comment by dougwilson** [comment] 2019-08-15 13:10
Right now it just inherits the timeout for a request set on your Node.js server module.exports.default

**Comment by dougwilson** [comment] 2019-08-15 13:12
Duplicate of #207

**Closed by dougwilson** 2019-08-15 13:12 UTC
