### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by th3nate** [expressjs/body-parser#299] opened 2018-04-01 12:25 UTC
hello,
i'm getting a lot of these errors on my API app and would like to know what can be done to catch them. 
the problem is that the client awaits response as the server hangs for about 2 min until finally throwing an error ..
also, i have a middleware to catch errors at the end of all routes but these errors doesn't seem to pass through it.

**edit**
it seems to be working fine for the first 20-30 min from the app initialization or when reloading the app, after that it starts rejecting all the post calls after the said timeout. (there are no cpu or memory spikes)

Help would be greatly appreciated, thanks!

```
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10)
     at emitNone (events.js:106:13)
     at IncomingMessage.emit (events.js:208:7)
     at abortIncoming (_http_server.js:424:9)
     at socketOnClose (_http_server.js:418:3)
     at emitOne (events.js:121:20)
     at Socket.emit (events.js:211:7)
     at _handle.close (net.js:567:12)
     at /app/node_modules/spdy-transport/lib/spdy-transport/stream.js:652:7
     at _combinedTickCallback (internal/process/next_tick.js:131:7)
     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by dougwilson** [comment] 2018-04-01 14:45
So that error should be explained in our docs: https://github.com/expressjs/body-parser/blob/master/README.md#request-aborted

Does it need to be expanded? We can always add more explanation, let us know :+1: You can see in your stack trace that the socket closed and thus `_http_server.js` from Node.js emitted the abort event which the raw-body module caught.

As for why your error middleware is not getting triggered, not sure. This module does not print errors anywhere, and just calls next(err). You were able to see that error because something in the app outside this module got the error and logged it. If you can provide an example app that reproduces the issue I can run, I can dig into it ;++;

**Comment by th3nate** [comment] 2018-04-01 14:58
hi @dougwilson and thanks for the quick reply,
so from what i understand this error doesn't have anything to do with the client's request rejections and server hang issues i'm having?

**Comment by dougwilson** [comment] 2018-04-01 15:32
Hm, I'm not sure. The error you posted is triggered whenever Node.js emits this event: https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_aborted and the stack trace looks like it was because the TCP connection was closed.

The Node.js folks may be able to provide better explaination on when Node.js emits that event, though. Perhaps if you can provide an example app that reproduces the issue I can run, I can dig into it :+1: and see if I can figure out something more.

**Comment by th3nate** [comment] 2018-04-01 15:38
i'd love to provide an example but the but unfortunately this only happens with a lot of traffic and concurrent requests, it doesn't replicate with a postman call :/

**Comment by dougwilson** [comment] 2018-04-01 16:35
Yea, weird. What are the next steps here that I can take to help?

**Comment by th3nate** [comment] 2018-04-01 17:00
not really sure, but i really appreciate your willingness to help with this, thank you.

**Comment by dougwilson** [comment] 2018-04-01 18:43
Yea, I don't know either. Always happy to help (I provided this code for free for everyone as a giant help, in fact!). If there is a way to reproduce it, I would usually attach a debugger and set a breakpoint in the code and try to walk through what is happening and combine it with a packet capture using Wireshark. I don't have a way to do this with the information provided thus far, so I don't know how else I can help, besides maybe you'd be able to perform those tasks and report back?

**Comment by th3nate** [comment] 2018-04-02 08:25
well i cant debug the production server that's where the problem occurs with the big traffic etc. but ill give the wireshark a go, and let you know

**Comment by dougwilson** [comment] 2018-04-02 12:39
This module doesn't output errors in any way. All errors are handed back to Express as error objects and Express will execute your error handling middleware. If you can provide example code demonstrating the error not getting into the Express error handler I can debug through it and see what is happening, but otherwise I have no idea how it can be logger and have not invoked through your error handling middleware.

**Comment by dougwilson** [comment] 2018-04-02 12:42
P.S. with so many issues constantly coming in from all the modules, I primarily interact with Github using email. When you edit a comment there is no email sent and the original email only contains the original text. You lucked out that I accidentally clicked the Github link and saw the edit, otherwise I would have never known you added a whole new section and wouldn't have ever responded.

**Comment by benjaminclot** [comment] 2018-04-25 13:58
I also get this error on production code (see my commit above for some sample code). I tried catching it with `app.use(function(err, req, res, next) {...` but it's not emitted from there.

**Comment by dougwilson** [comment] 2018-04-30 23:46
Closing since I never heard back from the OP. I can reopen if someone can provide complete code and instructions to reproduce. There is nothing I can do if no further information is provided besides waste my time. You're also welcome to make a pull request as well.

**Closed by dougwilson** 2018-04-30 23:46 UTC
Labels: awaiting more info

**Comment by omprakash-web** [comment] 2018-06-07 05:49
@dkozlovskyi  @dougwilson i am also facing this issue in my live server .. i didn't change anything in code but suddenly today am facing this issue .

Any solution to this it will really helps me a lot ??

**Comment by lxknvlk** [comment] 2018-06-07 09:36
Same here.
