### ISSUE TITLE
Getting ENETUNREACH errors when updating from 1.15.2 to 1.17.1

### ISSUE THREAD

**Issue by mvolz** [expressjs/body-parser#242] opened 2017-04-27 10:16 UTC
I have a series of mocha tests that try to resolve DOIs (i.e. http://doi.org/10.1007/11926078_68 redirects to http://link.springer.com/chapter/10.1007%2F11926078_68) and for some reason running these tests after updating body-parser causes individual tests to throw errors undeterministically. This is the error I get back from the request library I am using (preq)

```
{ Error: connect ENETUNREACH 2a05:d014:446:f01::d:443 - Local (:::0)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at connect (net.js:884:16)
    at net.js:1013:7
    at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/index.js:99:29
    at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/cache.js:72:25
    at RawTask.call (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/asap.js:40:19)
    at flush (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'HTTPError',
  message: '504: internal_http_error',
  status: 504,
  body: 
   { type: 'internal_http_error',
     description: 'Error: connect ENETUNREACH 2a05:d014:446:f01::d:443 - Local (:::0)',
     error: 
      { Error: connect ENETUNREACH 2a05:d014:446:f01::d:443 - Local (:::0)
          at Object.exports._errnoException (util.js:1018:11)
          at exports._exceptionWithHostPort (util.js:1041:20)
          at connect (net.js:884:16)
          at net.js:1013:7
          at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/index.js:99:29
          at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/cache.js:72:25
          at RawTask.call (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/asap.js:40:19)
          at flush (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/raw.js:50:29)
          at _combinedTickCallback (internal/process/next_tick.js:73:7)
          at process._tickCallback (internal/process/next_tick.js:104:9)
        cause: [Object],
        isOperational: true,
        code: 'ENETUNREACH',
        errno: 'ENETUNREACH',
        syscall: 'connect',
        address: '2a05:d014:446:f01::d',
        port: 443 },
     stack: 'Error: connect ENETUNREACH 2a05:d014:446:f01::d:443 - Local (:::0)\n    at Object.exports._errnoException (util.js:1018:11)\n    at exports._exceptionWithHostPort (util.js:1041:20)\n    at connect (net.js:884:16)\n    at net.js:1013:7\n    at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/index.js:99:29\n    at /home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/lib/cache.js:72:25\n    at RawTask.call (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/asap.js:40:19)\n    at flush (/home/marielle/Code/citoid/node_modules/service-runner/node_modules/dnscache/node_modules/asap/raw.js:50:29)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)',
     uri: 'https://dx.doi.org/10.1007/11926078_68',
     method: 'head' } }
```
As you may notice, the stack trace doesn't go into body-parser at all so this is a pretty unhelpful bug report :). I'll try to look into it more.

**Comment by dougwilson** [comment] 2017-04-27 15:54
That is weird indeed. Typically this module, `body-parser` is used in an Express server, but the error you posted above looks like an error from making an _outbound_ connection, which likely has no relating to this module. There isn't really enough information for me to even poke at anything here, so would it be possible to help me out with providing either a patch or enough to take a look at and help diagnose?

Perhaps the following:

1. Version of Node.js
2. Full code I can run and reproduce the issue.
3. Instructions on how to run.

Thanks!

**Comment by dougwilson** [comment] 2017-07-30 03:22
Closing since I never heard back.

**Closed by dougwilson** 2017-07-30 03:22 UTC
Labels: awaiting more info
